import './globals.css';
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
import Nav from './auth/Nav';
import QueryWrapper from '@/app/QueryWrapper';
import AuthContext from '@/app/auth/AuthContext';

const roboto = Roboto({
	subsets: ['latin'],
	weight: ['400', '700'],
	variable: '--font-roboto',
});

export const metadata: Metadata = {
	title: 'Greys Farm',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body
				className={` ${roboto.variable} h-screen font-sans  bg-light-background overflow-hidden`}
			>
				<QueryWrapper>
					<AuthContext>
						<Nav />
						<div className="mx-auto px-8 py-4 h-screen overflow-y-auto">{children}</div>
					</AuthContext>
				</QueryWrapper>
			</body>
		</html>
	);
}
